# Form implementation generated from reading ui file 'ui/designer/mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 109)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(300, 0))
        MainWindow.setMaximumSize(QtCore.QSize(300, 600))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cbox_connections = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cbox_connections.setObjectName("cbox_connections")
        self.horizontalLayout.addWidget(self.cbox_connections)
        self.toolbtn_manage = QtWidgets.QToolButton(parent=self.centralwidget)
        self.toolbtn_manage.setObjectName("toolbtn_manage")
        self.horizontalLayout.addWidget(self.toolbtn_manage)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btn_connect = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_connect.setEnabled(False)
        self.btn_connect.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_connect.setStyleSheet("QPushButton {\n"
"    border-radius: 60px;\n"
"    background-color: #4285F4;\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #3367D6;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #2A56C6;\n"
"}")
        self.btn_connect.setObjectName("btn_connect")
        self.horizontalLayout_2.addWidget(self.btn_connect)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OpenVPN3"))
        self.toolbtn_manage.setText(_translate("MainWindow", "..."))
        self.btn_connect.setText(_translate("MainWindow", "Connect"))
